### ISSUE TITLE
Base image for OVA

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/s-k8-releases#31]
For 0.3 release

**Comment by IslamHeggy** [comment]
This issue is about utilizng the OVA creation a little bit.

So what happens now is that every push to the master will create an image from scratch and then start setting up everything.

What we want to achieve create this image one time and then import it and copy the new code and output a new OVA. This will fasten the process of creating the OVA by the pipeline or even manually by 50 percent of the time.
